-- MySQL Script generated by MySQL Workbench
-- 07/27/15 17:26:47
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema thinkcms
-- -----------------------------------------------------
-- thinkcms
DROP SCHEMA IF EXISTS `thinkcms` ;
CREATE SCHEMA IF NOT EXISTS `thinkcms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `thinkcms` ;

-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_user_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_user_grade` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_user_grade` (
  `gid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gname` CHAR(20) NOT NULL DEFAULT '' COMMENT '会员等级',
  PRIMARY KEY (`gid`))
ENGINE = MyISAM
COMMENT = '会员等级';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_user` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_user` (
  `uid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` CHAR(20) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` CHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `login_ip` CHAR(20) NOT NULL DEFAULT '' COMMENT '登录IP',
  `login_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '登录时间',
  `reg_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '注册时间',
  `role` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1管理员2会员',
  `times` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '登录次数',
  `lock` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否锁定 0正常,1锁定',
  `grade_gid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '会员的等级',
  `nickname` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '昵称',
  `email` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '邮箱',
  PRIMARY KEY (`uid`),
  INDEX `fk_rb_user_rb_grade1_idx` (`grade_gid` ASC))
ENGINE = MyISAM
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_link` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_link` (
  `lid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(20) NOT NULL DEFAULT '' COMMENT '链接名称',
  `url` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '链接地址',
  `logo` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '链接logo',
  `addtime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
  `verifystate` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1审核中，2审核通过，3失败',
  `people` CHAR(20) NOT NULL DEFAULT '' COMMENT '申请人姓名',
  `phone` CHAR(11) NOT NULL DEFAULT '' COMMENT '申请人联系手机',
  `sort` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  `user_uid` INT UNSIGNED NOT NULL COMMENT '用户表关联',
  PRIMARY KEY (`lid`),
  INDEX `fk_rb_link_rb_user_idx` (`user_uid` ASC))
ENGINE = MyISAM
COMMENT = '友情链接表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_model` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_model` (
  `mid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(50) NOT NULL DEFAULT '' COMMENT '模型名称(英文)',
  `remark` CHAR(50) NOT NULL DEFAULT '' COMMENT '中文说明',
  PRIMARY KEY (`mid`))
ENGINE = MyISAM
COMMENT = '模型表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_type` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_type` (
  `typeid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `typename` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '类型名称',
  PRIMARY KEY (`typeid`))
ENGINE = MyISAM
COMMENT = '文档类型';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_category` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_category` (
  `cid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cname` CHAR(255) NOT NULL DEFAULT '' COMMENT '分类名称',
  `pid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父级id',
  `cat_type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1封面 2单一内容 3普通 4跳转',
  `go_url` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '跳转地址',
  `sort` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  `pic` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '栏目图片',
  `page` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '每一页记录数',
  `go_child` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 不跳转到子分类 1 跳转到子分类',
  `seo_title` VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'seo标题',
  `keywords` CHAR(80) NOT NULL DEFAULT '' COMMENT '关键字',
  `description` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '描述',
  `default_tpl` CHAR(20) NOT NULL DEFAULT '' COMMENT '封面模板',
  `list_tpl` CHAR(20) NOT NULL DEFAULT '' COMMENT '列表模板',
  `view_tpl` CHAR(20) NOT NULL DEFAULT '' COMMENT '视图模板',
  `model_mid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '模型关联外键',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '控制器',
  `type_typeid` INT UNSIGNED NOT NULL COMMENT '文档类型管理外键',
  `is_show` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否显示 1显示 0显示',
  PRIMARY KEY (`cid`),
  INDEX `fk_rb_category_rb_model1_idx` (`model_mid` ASC),
  INDEX `fk_thinkcms_category_thinkcms_type1_idx` (`type_typeid` ASC))
ENGINE = MyISAM
COMMENT = '栏目表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_article` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_article` (
  `aid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `article_title` CHAR(255) NOT NULL DEFAULT '' COMMENT '文档标题',
  `sort` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  `click` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '点击次数',
  `flag` SET('推荐','头条','图文') NULL COMMENT '属性',
  `is_top` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0不置顶 ，1置顶',
  `keywords` CHAR(80) NOT NULL DEFAULT '' COMMENT '关键字',
  `description` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '描述',
  `file` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '下载地址',
  `pic` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '原图',
  `addtime` INT NOT NULL DEFAULT 0 COMMENT '添加时间',
  `edittime` INT NOT NULL DEFAULT 0 COMMENT '编辑时间',
  `resource` CHAR(20) NOT NULL DEFAULT '' COMMENT '来源',
  `verifystate` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1审核中  2 审核通过  3审核失败',
  `tag` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'tag标签',
  `seo_title` CHAR(255) NOT NULL DEFAULT '' COMMENT 'seo标题',
  `tpl` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '模板',
  `user_uid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户表关联',
  `category_cid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '栏目表关联',
  PRIMARY KEY (`aid`),
  INDEX `fk_rb_article_rb_user1_idx` (`user_uid` ASC),
  INDEX `fk_rb_article_rb_category1_idx` (`category_cid` ASC))
ENGINE = MyISAM
COMMENT = '文档表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_config` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_config` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` CHAR(100) NOT NULL DEFAULT '' COMMENT '引用代码',
  `title` CHAR(80) NOT NULL DEFAULT '' COMMENT '中文说明',
  `body` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '具体信息',
  `config_type` TINYINT NOT NULL DEFAULT 2 COMMENT '1图片 2单行文本 3 多行文本',
  `group` ENUM('基本设置','更多设置') NOT NULL DEFAULT '基本设置',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '网站配置';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_position` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_position` (
  `psid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `position_name` CHAR(100) NOT NULL DEFAULT '' COMMENT '位置名称',
  `width` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '宽度',
  `height` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '高度',
  PRIMARY KEY (`psid`))
ENGINE = MyISAM
COMMENT = '广告位置';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_ad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_ad` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_ad` (
  `aid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(50) NOT NULL DEFAULT '' COMMENT '广告名称',
  `url` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '广告链接',
  `pic` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '广告图片',
  `addtime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
  `verifystate` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1 审核中，2审核通过 ，3不通过',
  `sort` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  `position_psid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '广告位置id',
  `user_uid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户表关联',
  PRIMARY KEY (`aid`),
  INDEX `fk_rb_ad_hd_position1_idx` (`position_psid` ASC),
  INDEX `fk_rb_ad_rb_user1_idx` (`user_uid` ASC))
ENGINE = MyISAM
COMMENT = '广告表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_attr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_attr` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_attr` (
  `attr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `attr_name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '类型说明',
  `type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1 单选， 2多选',
  `type_typeid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文档类型关联外键',
  `sort` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  `is_pic` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否需要有图集 1需要   0 不需要',
  PRIMARY KEY (`attr_id`),
  INDEX `fk_thinkcms_attr_thinkcms_type1_idx` (`type_typeid` ASC))
ENGINE = MyISAM
COMMENT = '文档属性，用于筛选';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_attr_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_attr_value` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_attr_value` (
  `attr_value_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `attr_value` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '属性值',
  `attr_attr_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文档属性关联外键',
  `attr_value_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称',
  `attr_value_sort` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  PRIMARY KEY (`attr_value_id`),
  INDEX `fk_think_attr_value_think_attr1_idx` (`attr_attr_id` ASC))
ENGINE = MyISAM
COMMENT = '文档类型默认值';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_article_pic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_article_pic` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_article_pic` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `big` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '大图',
  `medium` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '中图',
  `small` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '小图',
  `article_aid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文档关联外键',
  `attr_value_attr_value_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rb_pic_rb_article1_idx` (`article_aid` ASC),
  INDEX `fk_thinkcms_article_pic_thinkcms_attr_value1_idx` (`attr_value_attr_value_id` ASC))
ENGINE = MyISAM
COMMENT = '图集';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_model_field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_model_field` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_model_field` (
  `fid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fname` CHAR(20) NOT NULL DEFAULT '' COMMENT '字段名称英文',
  `title` CHAR(50) NOT NULL DEFAULT '' COMMENT '字段说明',
  `validate` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '1 数字，2 时间，3 手机号 ， 4 固定电话，5 邮箱， 6 网址，7英文',
  `require` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 选填 1必填',
  `show_type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1 文本 ，2多行文本 ，3 html ，4 单选框 ，5下拉框，6多选框 ，7文件上传框，8图片上传框 ， 9地区联动',
  `show_lists` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0显示列表页 1显示列表页',
  `is_system` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 不是系统字段 1 系统字段',
  `is_disabled` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '1禁用 0正常',
  `model_mid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '模型表关联外键',
  `sort` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  `error` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '错误提示',
  PRIMARY KEY (`fid`),
  INDEX `fk_rb_model_field_rb_model1_idx` (`model_mid` ASC))
ENGINE = MyISAM
COMMENT = '字段表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_model_field_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_model_field_value` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_model_field_value` (
  `fv_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `field_value` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '默认值',
  `field_fid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '字段表关联外键',
  PRIMARY KEY (`fv_id`),
  INDEX `fk_rb_model_field_value_rb_model_field1_idx` (`field_fid` ASC))
ENGINE = MyISAM
COMMENT = '字段默认值表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_feedback` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_feedback` (
  `fd_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `theme` CHAR(100) NOT NULL DEFAULT '' COMMENT '主题',
  `body` TEXT NULL COMMENT '内容',
  `addtime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '留言时间',
  `people` CHAR(20) NOT NULL DEFAULT '' COMMENT '联系人',
  `email` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '电子邮件',
  `tel` CHAR(10) NOT NULL DEFAULT '' COMMENT '固定电话',
  `phone` CHAR(11) NOT NULL DEFAULT '' COMMENT '手机',
  `lookstate` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1没有看 2已经阅读',
  `showstate` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0不显示 1显示',
  `pid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父级',
  `user_uid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '会员表关联外键',
  PRIMARY KEY (`fd_id`),
  INDEX `fk_hd_feedback_rb_user1_idx` (`user_uid` ASC))
ENGINE = MyISAM
COMMENT = '留言表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_user_baseinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_user_baseinfo` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_user_baseinfo` (
  `bid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `realname` CHAR(20) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `sex` ENUM('男','女') NOT NULL DEFAULT '男' COMMENT '性别',
  `birthday` DATE NULL COMMENT '生日',
  `qq` CHAR(15) NOT NULL DEFAULT '' COMMENT 'qq',
  `email` CHAR(60) NOT NULL DEFAULT '' COMMENT '邮箱地址',
  `phone` CHAR(11) NOT NULL DEFAULT '' COMMENT '手机号码',
  `face` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '头像',
  `user_uid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'user表关联外键',
  PRIMARY KEY (`bid`),
  INDEX `fk_rb_user_baseinfo_rb_user1_idx` (`user_uid` ASC))
ENGINE = MyISAM
COMMENT = '用户基本信息表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_article_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_article_data` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_article_data` (
  `article_aid` INT UNSIGNED NOT NULL COMMENT '主表关联外键',
  `body` TEXT NULL COMMENT '详细内容',
  INDEX `fk_rb_article_data_rb_article1_idx` (`article_aid` ASC))
ENGINE = MyISAM
COMMENT = '文章附表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_user_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_user_comment` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_user_comment` (
  `cmid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '评论内容',
  `addtime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论时间',
  `verifystate` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1审核中 2 审核通过  3 不通过',
  `article_aid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文章主表关联外键',
  `user_uid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户表关联外键',
  `pid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父级id',
  PRIMARY KEY (`cmid`),
  INDEX `fk_rb_user_comment_rb_article1_idx` (`article_aid` ASC),
  INDEX `fk_rb_user_comment_rb_user1_idx` (`user_uid` ASC))
ENGINE = MyISAM
COMMENT = '评论表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_relation_preview_grade_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_relation_preview_grade_category` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_relation_preview_grade_category` (
  `catid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '栏目id',
  `userid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户id',
  INDEX `fk_rb_relation_preview_grade_category_rb_category1_idx` (`catid` ASC),
  INDEX `fk_rb_relation_preview_grade_category_rb_grade1_idx` (`userid` ASC))
ENGINE = MyISAM
COMMENT = '会员等级查看栏目的权限表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_article_attr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_article_attr` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_article_attr` (
  `article_attr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `attr_value` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '属性值',
  `attr_attr_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文档属性表关联外键',
  `category_cid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '栏目关联外键',
  `article_aid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文档关联外键',
  `type_typeid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文档类型关联外键',
  `attr_value_attr_value_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '属性值表关联字段',
  `type` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '展示类型 1单选 2多选',
  `is_pic` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `attr_value` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '属性值',
  PRIMARY KEY (`article_attr_id`),
  INDEX `fk_thinkcms_article_attr_thinkcms_attr1_idx` (`attr_attr_id` ASC),
  INDEX `fk_thinkcms_article_attr_thinkcms_category1_idx` (`category_cid` ASC),
  INDEX `fk_thinkcms_article_attr_thinkcms_article1_idx` (`article_aid` ASC),
  INDEX `fk_thinkcms_article_attr_thinkcms_type1_idx` (`type_typeid` ASC),
  INDEX `fk_thinkcms_article_attr_thinkcms_attr_value1_idx` (`attr_value_attr_value_id` ASC))
ENGINE = MyISAM
COMMENT = '文档和属性表关联中间表';


-- -----------------------------------------------------
-- Table `thinkcms`.`thinkcms_upload`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkcms`.`thinkcms_upload` ;

CREATE TABLE IF NOT EXISTS `thinkcms`.`thinkcms_upload` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ext` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '文件扩展名',
  `remark` VARCHAR(200) NOT NULL DEFAULT 0 COMMENT '文件原名称',
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '文件名称',
  `path` VARCHAR(255) NOT NULL,
  `size` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文件大小',
  `addtime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
  `article_aid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文档关联表外键',
  `user_uid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户表关联外键',
  `category_cid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '栏目表关联外键',
  `config_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '系统设置表关联外加',
  PRIMARY KEY (`id`),
  INDEX `fk_thinkcms_upload_thinkcms_article1_idx` (`article_aid` ASC),
  INDEX `fk_thinkcms_upload_thinkcms_user1_idx` (`user_uid` ASC),
  INDEX `fk_thinkcms_upload_thinkcms_category1_idx` (`category_cid` ASC),
  INDEX `fk_thinkcms_upload_thinkcms_config1_idx` (`config_id` ASC))
ENGINE = MyISAM
COMMENT = '编辑器图片表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
